//
//  LoginModels.swift
//  TodoList
//
//  Created by Konstantin Pimbursky on 05.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoginModels {
	struct Request {
		var login: String
		var password: String
	}
	
	struct Response {
		var success: Bool
		var login: String
		var lastLoginDate: Date
	}
	
	struct ViewModel {
		var success: Bool
		var userName: String
		var lastLoginDate: String
	}
}
