//
//  LoginInteractor.swift
//  TodoList
//
//  Created by Konstantin Pimbursky on 05.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ILoginInteractor {
	func login(request: LoginModels.Request)
}

class LoginInteractor: ILoginInteractor {
	private var presenter: ILoginPresenter
	private var worker: ILoginWorker
	
	init(presenter: ILoginPresenter, worker: ILoginWorker) {
		self.presenter = presenter
		self.worker = worker
	}
	
	func login(request: LoginModels.Request) {
		let result = worker.login(login: request.login, password: request.password)
		
		let response = LoginModels.Response(
			success: result.success != 0,
			login: result.login,
			lastLoginDate: result.lastLoginDate
		)
		presenter.present(response: response)
	}
}
